Azure/ng-deploy-azure

- package-lock.json
- package.json
js-yaml was reported as a security vulnerability. I updated this to to fix it.
> npm audit fix for js-yaml

- package.json
adding author and collaborators.  John, Shayne, let me know if you want to be listed and with what info?
> adding author and collaborators

- package.json
updating version of package to what we will soon have in NPM
As soon as this version have landed in NPM we should update README to say to `npm install @azure/ng-deploy`
Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).
Please add yourself as the assignee
Please add relevant projects so this issue can be properly tracked.
> bumping package version to reflect what will soon be on NPM

- package.json
Improvements to package.json metadata for npm display and general use cases.
- Most changes will only impact the display of this module on npm. AFAIK there's no way to mock that out, so npm publish is the only way to actually validate outside of basic JSON validation.
> Improvements to package.json metadata

- .gitignore
- README.md
- Cleaned up the README
- Added instructions to open the site in the browser
- Clarified how to build the project (this is needed for now due to issue #23)
- Added more links in resource section at the bottom and some throughout
- Removed note about this not being on npm, as it is now
- Updated instructions where needed, to be clearer
> README Fixes

- package.json
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Replace this with instructions on how to test this PR
Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).
Please add yourself as the assignee
Please add relevant projects so this issue can be properly tracked.
> feat: updated dependency

- .gitignore
- package.json
- src/@types/ascii-progress.d.ts
- src/@types/progress.d.ts
- src/builders/actions/deploy.ts
- src/builders/deploy.builder.ts
- src/util/prompt/__mocks__/spinner.ts
- Fix install by switching `ascii-progress` to `progress` package
- Fix deploy command on windows
Use the deploy builder on a windows machine.
/
@sinedied 
/
> fix: install & windows deployment

- src/util/workspace/angular-json.ts
Fix package name in generated `angular.json`, otherwise it's not working
- Follow the tutorial :)
Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).
@sinedied 
/
> fix: package name in angular.json file

- azure-pipelines.yml
- package.json
adding the following to azure pipelines:
- adding unit test step
- adding strategy for different OS
- Replace this with instructions on how to test this PR
Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).
Please add yourself as the assignee
Please add relevant projects so this issue can be properly tracked.
> adding fixes to pipeline file

- README.md
The logout command in Readme was wrong. Instead of "logout" it's "azureLogout".
N/A
N/A
@shmool 
N/A
> fix logout instructions

- CONTRIBUTING.md
Fix local dev doc
/
/
@sinedied 
/
> doc: fix local development instructions

- README.md
- package.json
- src/builders/actions/deploy.ts
- src/ng-add/index.spec.ts
- src/ng-add/index.ts
- src/util/azure/__mocks__/auth.ts
- src/util/azure/auth.spec.ts
- src/util/azure/auth.ts
We are introducing support for CI mode: When trying to run a continuous deployment process (eg. from GitHub Actions), the interactive login mode blocks the CI.
This new features will switch to a different login process if CI is detected.
- Tests have been added, just run `npm test`
Put closes #52in your comment to auto-close the issue that your PR fixes (if such).
@manekinekko
> feat: add support for CI

- src/util/azure/auth.ts
Somehow the underlying SDK was keeping a copy of the cache from previous auths processes. However, that cache was corrupted and some creds were undefined (`username` and `tokenAudience`).
See https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/215
> fix: guard against corrupted user creds

- src/util/azure/auth.ts
This PR fixes the `creds.getToken is not a function` we started having recently.
> fix: guard against corrupted getToken function

- package.json
- src/util/azure/account.ts
this fixes an issue where this piece of code ended up in while/true 
```
function accountNameGenerator(client: StorageManagementClient) {
return async (name: string) => {
return await generateName(name, checkNameAvailability(client, false));
};
}
```
- place a console.log inside of `checkNameAvailability()` and you will see this being hit thousands of times
Closes #60
> fix: issue where it generates names for all eternity

- CONTRIBUTING.md
- package.json
Since we all started to use conventional commits, this PR make sure we enforce it.
The contributing guide was updated in accordance.
> chore: enforce conventional commits

- src/util/azure/account.ts
- src/util/azure/resource-group.ts
> fix: change default resource group and storage account names

- README.md
- src/builders/actions/deploy.ts
- src/builders/deploy.builder.ts
When running `ng deploy` the project runs a specified target before deploying.
The target is specified in `azure.json` under `hosting[i].app.target`, and an optional configuration under `hosting[i].app.configuration`. The default is `hosting[i].app.target = "build"` and `hosting[i].app.configuration = "production"`. 
Then the files are fetched from the path specified in the target's configuration in `angular.json` under `outputPath`. If an `outputPath` is not specified, or a build target is not specified in `azure.json`, a `path` where the files to be deployed exist must be provided in `azure.json` instead.
The purpose of this change is to make sure the deployed files are the latest version of the application, while allowing the users to configure a different build strategy.
- Default: …
> fix: run build target before deploy, with an option to change it

- README.md
There were 2 sentences that didn't sound right. This PR attempts to offer a slight improvement.
- Change to the README.md file.
[branedmg](https://github.com/branedmg)
> docs: fix 2 small typos

- src/builders/deploy.schema.json
- src/builders/logout.schema.json
- src/ng-add/schema.json
> An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
